#!/usr/bin/env bash
#
# ArchiAgents CLI - Quick Reference Guide
#
# This script provides quick examples of all CLI commands

echo "======================================================================"
echo "ArchiAgents CLI - Quick Reference"
echo "======================================================================"
echo ""

echo "1. PROJECT MANAGEMENT"
echo "---------------------------------------------------------------------"
echo "# Initialize a new project"
echo "python archiagents.py project init --name \"Digital Transformation\" --enterprise \"TechCorp\""
echo ""
echo "# List all projects"
echo "python archiagents.py project list"
echo ""
echo "# Show project status"
echo "python archiagents.py project status"
echo ""
echo "# Delete a project"
echo "python archiagents.py project delete my_project --force"
echo ""

echo "2. TOGAF PHASE EXECUTION"
echo "---------------------------------------------------------------------"
echo "# Execute Phase A (Architecture Vision)"
echo "python archiagents.py phase run phase-a"
echo ""
echo "# Execute phase with AI agents"
echo "python archiagents.py phase run phase-a --use-ai"
echo ""
echo "# List all phases and their status"
echo "python archiagents.py phase list"
echo ""
echo "# Check phase status"
echo "python archiagents.py phase status phase-a"
echo ""
echo "# Reset a phase"
echo "python archiagents.py phase reset phase-a --force"
echo ""

echo "3. RUNTIME INTELLIGENCE"
echo "---------------------------------------------------------------------"
echo "# Analyze architecture"
echo "python archiagents.py intelligence analyze"
echo ""
echo "# Make an architecture decision"
echo "python archiagents.py intelligence decide --title \"Cloud Migration\" --type strategic"
echo ""
echo "# Check architecture health"
echo "python archiagents.py intelligence health"
echo ""
echo "# Generate intelligence report"
echo "python archiagents.py intelligence report --output report.txt"
echo ""

echo "4. REAL-WORLD SCENARIOS"
echo "---------------------------------------------------------------------"
echo "# List available scenarios"
echo "python archiagents.py scenario list"
echo ""
echo "# Describe a scenario"
echo "python archiagents.py scenario describe cloud-migration"
echo ""
echo "# Run a complete scenario"
echo "python archiagents.py scenario run cloud-migration --enterprise \"TechCorp\" --use-ai"
echo ""
echo "# Run scenario in fast mode (no confirmations)"
echo "python archiagents.py scenario run digital-transformation --fast --autonomous"
echo ""

echo "5. CONFIGURATION"
echo "---------------------------------------------------------------------"
echo "# Show current configuration"
echo "python archiagents.py config show"
echo ""
echo "# Set configuration value"
echo "python archiagents.py config set ai.provider openai"
echo ""
echo "# Get configuration value"
echo "python archiagents.py config get ai.provider"
echo ""

echo "======================================================================"
echo "For detailed help on any command, use:"
echo "  python archiagents.py COMMAND --help"
echo "======================================================================"
