#!/bin/bash
# ArchiAgents Model Generation - Quick Reference Examples

echo "==================================================================="
echo "  ArchiAgents Model Generation - Quick Reference"
echo "==================================================================="
echo ""

echo "### 1. ARCHIMATE MODEL GENERATION ###"
echo ""

echo "# Generate Business Layer Model"
echo "python archiagents.py model generate \\"
echo "  --type archimate-business \\"
echo "  --name \"Business Architecture Model\" \\"
echo "  --format text --format mermaid --format archi"
echo ""

echo "# Generate Multi-Layer Enterprise Model"
echo "python archiagents.py model generate \\"
echo "  --type archimate-multi-layer \\"
echo "  --name \"Enterprise Architecture\" \\"
echo "  --format text --format mermaid --format gojs --format ea"
echo ""

echo "# Generate Application Layer Model"
echo "python archiagents.py model generate \\"
echo "  --type archimate-application \\"
echo "  --name \"Application Architecture\" \\"
echo "  --format mermaid --format archi"
echo ""

echo "# Generate Technology Layer Model"
echo "python archiagents.py model generate \\"
echo "  --type archimate-technology \\"
echo "  --name \"Technology Architecture\" \\"
echo "  --format text --format ea"
echo ""

echo "### 2. BPMN PROCESS GENERATION ###"
echo ""

echo "# Generate BPMN Process Model"
echo "python archiagents.py model generate \\"
echo "  --type bpmn-process \\"
echo "  --name \"Order Fulfillment Process\" \\"
echo "  --format mermaid --format kroki"
echo ""

echo "# Generate Customer Onboarding Process"
echo "python archiagents.py model generate \\"
echo "  --type bpmn-process \\"
echo "  --name \"Customer Onboarding\" \\"
echo "  --format text --format mermaid"
echo ""

echo "### 3. UML DIAGRAM GENERATION ###"
echo ""

echo "# Generate UML Class Diagram"
echo "python archiagents.py model generate \\"
echo "  --type uml-class \\"
echo "  --name \"Domain Model\" \\"
echo "  --format mermaid --format ea"
echo ""

echo "# Generate UML Sequence Diagram"
echo "python archiagents.py model generate \\"
echo "  --type uml-sequence \\"
echo "  --name \"User Authentication Flow\" \\"
echo "  --format mermaid --format kroki"
echo ""

echo "# Generate UML Use Case Diagram"
echo "python archiagents.py model generate \\"
echo "  --type uml-use-case \\"
echo "  --name \"System Use Cases\" \\"
echo "  --format text --format mermaid"
echo ""

echo "# Generate UML Component Diagram"
echo "python archiagents.py model generate \\"
echo "  --type uml-component \\"
echo "  --name \"System Components\" \\"
echo "  --format mermaid --format ea"
echo ""

echo "# Generate UML Deployment Diagram"
echo "python archiagents.py model generate \\"
echo "  --type uml-deployment \\"
echo "  --name \"Deployment Architecture\" \\"
echo "  --format text --format mermaid"
echo ""

echo "### 4. MODEL MANAGEMENT ###"
echo ""

echo "# List All Models"
echo "python archiagents.py model list"
echo ""

echo "# List Models in JSON Format"
echo "python archiagents.py model list --format json"
echo ""

echo "# List Models in Tree View"
echo "python archiagents.py model list --format tree"
echo ""

echo "### 5. MODEL VALIDATION ###"
echo ""

echo "# Validate Model Against Standards"
echo "python archiagents.py model validate archimate_business_20251022 \\"
echo "  --standards archimate togaf"
echo ""

echo "# Validate UML Model"
echo "python archiagents.py model validate uml_class_20251022 \\"
echo "  --standards uml"
echo ""

echo "### 6. MODEL EXPORT ###"
echo ""

echo "# Export to Mermaid"
echo "python archiagents.py model export archimate_business_20251022 \\"
echo "  --format mermaid \\"
echo "  --output business_model.mmd"
echo ""

echo "# Export to Archi XML"
echo "python archiagents.py model export archimate_business_20251022 \\"
echo "  --format archi \\"
echo "  --output business_model.xml"
echo ""

echo "# Export to Enterprise Architect"
echo "python archiagents.py model export uml_class_20251022 \\"
echo "  --format ea \\"
echo "  --output domain_model.xmi"
echo ""

echo "# Export to GoJS JSON"
echo "python archiagents.py model export archimate_application_20251022 \\"
echo "  --format gojs \\"
echo "  --output app_model.json"
echo ""

echo "# Export to Kroki/PlantUML"
echo "python archiagents.py model export bpmn_process_20251022 \\"
echo "  --format kroki \\"
echo "  --output process.puml"
echo ""

echo "### 7. MODEL IMPROVEMENT ###"
echo ""

echo "# Get AI Improvement Suggestions"
echo "python archiagents.py model improve archimate_business_20251022"
echo ""

echo "# Get Suggestions for UML Model"
echo "python archiagents.py model improve uml_class_20251022"
echo ""

echo "### 8. COMPLETE WORKFLOW EXAMPLES ###"
echo ""

echo "# Example 1: TOGAF Phase B Business Architecture"
echo "python archiagents.py model generate \\"
echo "  --type archimate-business \\"
echo "  --name \"Phase B - Business Architecture\" \\"
echo "  --format text --format mermaid --format archi"
echo ""
echo "python archiagents.py model validate LATEST_MODEL_ID \\"
echo "  --standards archimate togaf"
echo ""
echo "python archiagents.py model improve LATEST_MODEL_ID"
echo ""

echo "# Example 2: Complete Software Design"
echo "# Domain Model"
echo "python archiagents.py model generate --type uml-class --name \"Domain Model\""
echo ""
echo "# Sequence Diagrams"
echo "python archiagents.py model generate --type uml-sequence --name \"User Flow\""
echo ""
echo "# Components"
echo "python archiagents.py model generate --type uml-component --name \"System Components\""
echo ""
echo "# Deployment"
echo "python archiagents.py model generate --type uml-deployment --name \"Deployment View\""
echo ""

echo "# Example 3: Multi-Format Export for Documentation"
echo "MODEL_ID=\"archimate_business_20251022\""
echo ""
echo "python archiagents.py model export \$MODEL_ID --format text --output docs/architecture.md"
echo "python archiagents.py model export \$MODEL_ID --format mermaid --output docs/diagram.mmd"
echo "python archiagents.py model export \$MODEL_ID --format archi --output models/archi.xml"
echo "python archiagents.py model export \$MODEL_ID --format gojs --output web/model.json"
echo ""

echo "### 9. SUPPORTED MODEL TYPES ###"
echo ""
echo "ArchiMate (7 types):"
echo "  - archimate-strategy"
echo "  - archimate-business"
echo "  - archimate-application"
echo "  - archimate-technology"
echo "  - archimate-physical"
echo "  - archimate-implementation"
echo "  - archimate-multi-layer"
echo ""
echo "BPMN (1 type):"
echo "  - bpmn-process"
echo ""
echo "UML (12 types):"
echo "  - uml-class"
echo "  - uml-sequence"
echo "  - uml-use-case"
echo "  - uml-activity"
echo "  - uml-state"
echo "  - uml-component"
echo "  - uml-deployment"
echo "  - uml-object"
echo "  - uml-package"
echo "  - uml-timing"
echo "  - uml-communication"
echo "  - uml-interaction-overview"
echo ""

echo "### 10. SUPPORTED OUTPUT FORMATS ###"
echo ""
echo "  - text      : Markdown documentation"
echo "  - mermaid   : Mermaid diagram syntax"
echo "  - kroki     : PlantUML for Kroki service"
echo "  - archi     : Archi tool XML format"
echo "  - gojs      : GoJS JSON for web visualization"
echo "  - ea        : Enterprise Architect XMI format"
echo ""

echo "==================================================================="
echo "  For detailed documentation, see MODEL_GENERATION_GUIDE.md"
echo "==================================================================="
